### ISSUE TITLE
__git_complete not found with bash v5.0.2(1)-release and bash-completion@2 v2.8

### ISSUE THREAD

**Issue by zeusdeux** [scop/bash-completion#278] opened 2019-02-01 14:42 UTC
## Environment

- macOS Mojave 10.14.1
- Homebrew 1.9.3-104-g277e8d4
- Homebrew/homebrew-core (git revision 1b878; last commit 2019-02-01)
- Homebrew/homebrew-cask (git revision 5ab27; last commit 2019-02-01)
- bash version `5.0.2(1)-release`

## Steps to reproduce (using `homebrew` as the package manager)

- `brew upgrade bash bash-completion@2`
- open a new shell
- run `__git_complete`

## Expected

`complete: usage: complete [-abcdefgjksuv] [-pr] [-DEI] [-o option] [-A action] [-G globpat] [-W wordlist]  [-F function] [-C command] [-X filterpat] [-P prefix] [-S suffix] [name ...]`

## Actual

`-bash: __git_complete: command not found`

## Things tried

- I have tried updating command in the bash dotfile to the new `[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"` but to no avail
- I have also tried to manually run the scripts mentioned in the "Caveats" section that is show post install but that didn't work either

## Workaround

Finally, I can confirm that bash-completion@2 v2.7 works with bash v5.0.2 and am currently using this workaround. To do so —

1. Open your shell
2. Type `brew edit bash-completion@2` and hit enter
3. Paste the contents of [the version of `bash-completion@2` in this commit](https://github.com/Homebrew/homebrew-core/blob/16ebe5f1843e6cb54856311ff0f676be53007329/Formula/bash-completion@2.rb) from homebrew-core
4. Run `brew unlink bash-completion@2 && brew install bash-completion@2`
5. Source your shell init file and you should've all your completions working again.

Any help on this would be much appreciated! Thanks!

**Comment by scop** [comment] 2019-02-01 15:05
I'm fairly certain that `__git_complete` is not meant to be run directly like that; that's the error output it gives even when things are working (on my Ubuntu box). But aside, the git completion is not shipped by this project, and I'm fairly certain that this is kind of a duplicate of #277.

**Closed by scop** 2019-02-01 15:05 UTC

**Comment by zeusdeux** [comment] 2019-02-02 18:45
I use it to setup git completion for custom aliases. For example: 
```sh
alias gc="git clone"
__git_complete gc _git_clone
```

Nevertheless, thanks for the heads up!

**Comment by FranklinYu** [comment] 2019-06-19 18:35
@scop What's the recommended way to add completion for Git aliases? It is very common to have Bash alias for Git commands.

**Comment by scop** [comment] 2019-06-19 20:15
I don't have a suggestion for that offhand.

**Comment by zeusdeux** [comment] 2019-06-19 21:41
If it helps, I downgraded to a version that works and pinned the version 🤷🏻‍♂️

**Comment by annaet** [comment] 2019-07-29 10:14
I had the same issue but it turned out it was because I was using `__git_complete` in my `.bash_profile` before running the bash completion script:

`[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"`

Adding the above line before using the command fixed this for me.

**Comment by zeusdeux** [comment] 2019-07-29 11:38
@annaet did that work with the latest release of bash-completion?

**Comment by annaet** [comment] 2019-07-29 16:58
@zeusdeux yes that's using bash-completion@2

**Comment by zeusdeux** [comment] 2019-07-29 17:06
@annaet thank you! 🙇🏻‍♂️

**Comment by zorzella** [comment] 2022-05-03 19:01
I had the same problem, but it seems that if you first run this command, then `__git_complete` works:

```
$ source /usr/share/bash-completion/completions/git
```

**Comment by ewall** [comment] 2023-10-02 14:25
I found the git completions script at `/opt/homebrew//etc/bash_completion.d/git-completion.bash` and just needed to source it to get the completions and `__git_complete` method to work... bash-completion@2 wasn't running it.
