### ISSUE TITLE
getting syntax error: invalid arithmetic operator (error token is "...")

### ISSUE THREAD

**Issue by jhrv** [scop/bash-completion#357] opened 2019-10-26 22:35 UTC
System info:

MacOS 10.14.6

```
~ $ bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)

~ $ brew info bash-completion@2
bash-completion@2: stable 2.8 (bottled), HEAD
...
```
----------------

This might not be a bash-completion issue, but I hope at least by explaining the issue that I could get some help debugging the issue.

The issue is this:

`$ a.b [tab]`

yields

`$ a.b bash: a.b: syntax error: invalid arithmetic operator (error token is ".b")`

If I source bash_completion like so:

`$ source /usr/local/share/bash-completion/bash_completion`

everything works like expected:

`$ a.b [tab] [tab]`

yields

```
$ a.b
folder/
binary
...
```
like expected.

In my .bashrc I have the following
```
  export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
  [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
``` 

I have also tried explicitly sourcing  /usr/local/Cellar/bash-completion@2/2.8/share/bash-completion/bash_completion in my bashrc, but seems to have no effect. For some reason it only works when I do it in my shell.

**Comment by scop** [comment] 2019-10-27 13:11
See "Troubleshooting" in README.md.

**Comment by jhrv** [comment] 2019-10-27 19:42
I've tried sourcing bash_completion also in my .bash_profile, also my .bash_profile only sources .bashrc so this should be ok. 
I've tried to run the same commands with `set +v` and `set +x`, but not getting any more useful output.  

Or was there any other sections in the Troubleshooting guide you would recommend?

**Comment by scop** [comment] 2019-10-27 20:24
To get a trace what's happening when you hit tab, you should be running under e.g. `set -x`, not `set +x` (which turns it off).

**Comment by jhrv** [comment] 2019-10-27 21:13
Thanks. When running `$ a.b [tab]` now yields:

```
$ a.b + local cmd=a.b
+ __load_completion a.b
+ dirs=(${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions)
+ local -a dirs
+ local 'OIFS=
' IFS=: dir cmd=a.b compfile
+ for dir in ${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
+ dirs+=($dir/bash-completion/completions)
+ for dir in ${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
+ dirs+=($dir/bash-completion/completions)
+ IFS='
'
+ [[ /usr/local/share/bash-completion/bash_completion == */* ]]
+ dirs+=("${BASH_SOURCE%/*}/completions")
+ for dir in "${dirs[@]}"
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/Users/hrv/.local/share/bash-completion/completions/a.b
+ [[ -f /Users/hrv/.local/share/bash-completion/completions/a.b ]]
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/Users/hrv/.local/share/bash-completion/completions/a.b.bash
+ [[ -f /Users/hrv/.local/share/bash-completion/completions/a.b.bash ]]
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/Users/hrv/.local/share/bash-completion/completions/_a.b
+ [[ -f /Users/hrv/.local/share/bash-completion/completions/_a.b ]]
+ for dir in "${dirs[@]}"
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/local/share/bash-completion/completions/a.b
+ [[ -f /usr/local/share/bash-completion/completions/a.b ]]
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/local/share/bash-completion/completions/a.b.bash
+ [[ -f /usr/local/share/bash-completion/completions/a.b.bash ]]
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/local/share/bash-completion/completions/_a.b
+ [[ -f /usr/local/share/bash-completion/completions/_a.b ]]
+ for dir in "${dirs[@]}"
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/share/bash-completion/completions/a.b
+ [[ -f /usr/share/bash-completion/completions/a.b ]]
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/share/bash-completion/completions/a.b.bash
+ [[ -f /usr/share/bash-completion/completions/a.b.bash ]]
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/share/bash-completion/completions/_a.b
+ [[ -f /usr/share/bash-completion/completions/_a.b ]]
+ for dir in "${dirs[@]}"
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/local/share/bash-completion/completions/a.b
+ [[ -f /usr/local/share/bash-completion/completions/a.b ]]
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/local/share/bash-completion/completions/a.b.bash
+ [[ -f /usr/local/share/bash-completion/completions/a.b.bash ]]
+ for compfile in "$cmd" "$cmd.bash" "_$cmd"
+ compfile=/usr/local/share/bash-completion/completions/_a.b
+ [[ -f /usr/local/share/bash-completion/completions/_a.b ]]
bash: a.b: syntax error: invalid arithmetic operator (error token is ".b")
history -a;
++ history -a


```

**Comment by scop** [comment] 2019-10-28 14:45
Ah, right, that's fixed in commit a47bd375bb0f95dc6d388d4097c420bddb72ae33 which is included in 2.9.

**Comment by scop** [comment] 2019-10-28 14:47
...or probably not after all, actually. Anyway I'll try to have a closer look soon.

**Comment by scop** [comment] 2019-10-28 15:24
I believe the error occurs when we try to access the _xspecs associative array to check if there's a completion for `a.b` there. I can simulate the error for a non-associative array:
```
$ declare -a a1; echo ${a1[a.b]}
bash: a.b: syntax error: invalid arithmetic operator (error token is ".b")
```
...but `_xspecs` _is_ defined as an associative array, and I cannot reproduce with such one:
```
$ declare -A a2; echo ${a2[a.b]}
# no errors, nothing, as expected
```
AFAIK it's like that in 2.8 too, so I have no more ideas at the moment.

**Comment by jhrv** [comment] 2019-10-28 15:46
I see. Like mentioned, this works when I explicitly source bash_completion again in my shell, even though I do it in my `.bashrc` as well - which sounds wierd. Any way to verify that the sourcing operation done in `.bashrc` was successful?

**Comment by scop** [comment] 2019-10-28 16:04
`bash --norc` gives you a "clean" shell, you can do `set -x` there and invoke the same commands your shell does when it starts up. I'd first triple check that what you manually source in your shell is the same bash_completion your rcfiles do.

**Comment by jhrv** [comment] 2019-10-28 19:08
I found out what the issue was. I was sourcing bash-completion from a function in my `.bashrc` file, and that resulted in some scoping issues (https://unix.stackexchange.com/questions/151889/why-does-bashs-source-command-behave-differently-when-called-from-a-function)
Thank very much for help with debugging this.

**Closed** 2019-10-29 16:32 UTC
