### ISSUE TITLE
auto completion added backslash before $

### ISSUE THREAD

**Issue by Mark-Joy** [scop/bash-completion#568] opened 2021-08-06 13:20 UTC
## Describe the bug

Auto completion added backslash before my variable caused it unable to goes further, also broke the command.

## To reproduce

```
λ [~] $ cd $PREFIX/
bin/     include/ libexec/ share/   var/
etc/     lib/     opt/     tmp/
λ [~] $ cd \$PREFIX/bin/

λ [~] $ ls $PREFIX/
README.md  etc/       lib/       opt/       tmp/
bin/       include/   libexec/   share/     var/
λ [~] $ ls \$PREFIX/README.md
```

## Expected behavior

Shall not add backslash before my variable.
## Versions (please complete the following information)

- [ ] Operating system name/distribution and version: Android Pie + Termux
- [ ] bash version, `echo "$BASH_VERSION"`: 5.1.8(1)-release
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.11

**Comment by akinomyoga** [comment] 2021-08-31 01:40
This seems like a duplicate of #290, #438, and #516.

**Closed** 2021-09-02 16:10 UTC
Labels: duplicate
