### ISSUE TITLE
Completing a relative path with a space and softlinks inside, turns it absolute (which breaks creating relative softlinks)

### ISSUE THREAD

**Issue by navid-zamani** [scop/bash-completion#1223] opened 2024-06-21 16:24 UTC
## Describe the bug

Double-completing a *relative* path with a *space* in the name and *softlinks* inside it, results in it being turned into an *absolute* path.  
This breaks attempts at passing relative paths to commands (like is common with `ln`).

## To reproduce

0. `cd /tmp; mkdir TEST; cd TEST`
1. `mkdir -p 'aaa/c c' 'aaa/xxx' 'aaa/yyy' bbb`
2. `cd 'aaa/c c/'`
3. `ln -s ../xxx; ln -s ../yyy`
4. `cd ../../bbb`
5. `ln -s ../aaa/c` and press ⟨TAB⟩ once, to get `../aaa/c\ c/`.
6. Press ⟨TAB⟩ again. And get `/tmp/TEST/aaa/c\ c/`.

## Expected behavior

One should get `../aaa/c\ c/` with
`xxx/ yyy/`
as suggestions.

## Versions (please complete the following information)

- [x] Operating system name/distribution and version: **Linux Mint 21.3 Virginia**
- [x] bash version, `echo "$BASH_VERSION"`: **5.1.16(1)-release**
- [x] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: **2.11**

## Additional context

It doesn’t happen, if there are no softlinks inside `'c c'`, of if there is no space in the name of that directory.  
But a very similar problem happens for tilde (**`~`**). Which needs fixing for the same reason.  
Also, I haven’t checked but suspect that if it transforms it like `realpath` does, turning any softlink component into the real path. (Which also breaks creating softlinks that use these other softlinks to work in several different environments.)

In my case I have several computers all syncing the same directories, but into a different base path since software expects those exact locations. Relative softlinks and softlinks that use other softlinks in their paths are the only way to get all paths to work on all systems. Especially since one of them is a Termux install on Android, where things like bind mounts don’t work, some paths (like pictures) are forcibly somewhere else, and `$HOME` is very different.

## Debug trace

[trace.log](https://github.com/user-attachments/files/15930187/trace.log)

**Comment by akinomyoga** [comment] 2024-06-22 07:05
I cannot reproduce the problem. I also tried the combination of the reported versions, Bash-5.1.16 and bash-completion-2.11, but the problem doesn't arise. The provided `trace.log` doesn't seem to contain any `/tmp/TEST/aaa/c c` except the very last line (which is printed by Bash).

What are the result of the following commands (before and after the problem is triggered)?

```bash
$ complete -p ln
$ declare -p toks
$ shopt -p localvar_inherit
```

What are the results of the following commands?

```bash
$ echo "[$-]"
$ echo "$BASH_OPTS"
$ bind -v
```

**Comment by scop** [comment] 2024-11-13 21:04
Closing due to lack of further info regarding the reproducer. Let's reopen if we receive that later.

**Closed by scop** 2024-11-13 21:04 UTC
