### ISSUE TITLE
find: bash error when completing argument before -exec (again)

### ISSUE THREAD

**Issue by leisti** [scop/bash-completion#646] opened 2021-11-04 15:13 UTC
## Describe the bug

When attempting to complete the `AB` argument in a `find` command such as `find AB -exec ...`, Bash gives this error: `COMP_POINT: substring expression < 0`

## To reproduce

1. Type this on the Bash command line, and press Enter: `find AB -type f -exec chmod a-w {} \;`
2. Move the cursor to just after text `AB`.
3. Press the tab key.

## Observed behavior

Bash outputs: `find ABbash: COMP_POINT: substring expression < 0`. This does not depend on whether or not `AB` should, in fact, be expanded to anything.

## Expected behavior

If a subdirectory `ABC` exists, but no others that start with `AB`: `AB` completed to `ABC`.

If no subdirectories that start with `AB` exist: nothing happens.

## Versions

- [ ] Operating system name/distribution and version: Xubuntu 21.10
- [ ] Terminal program name and version: xfce4-terminal, 0.8.10-1 (amd64)
- [ ] bash version: 5.1.8(1)-release (package version: 5.1-3ubuntu2 (amd64))
- [ ] bash-completion version: 2.11 (package version: 1:2.11-2ubuntu1 (all))

## Additional context

My `.bashrc` file includes the following lines. The debug trace shows that the last command executed is the one-line function `parse_git_branch`. However, the error does occur before that point.

```
# Save the history after each command, to make one terminal session's command history available for
# the others.
PROMPT_COMMAND='history -a; history -r'
...
export PS1="$USER_COLOR\u$NO_COLOR@$HOST_COLOR\h $PWD_COLOR\w"
if test -n "$(type -t git)"; then
    # Git has been installed, so display the current git branch in the command prompt.
    function parse_git_branch {
        git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(git: \1)/'
    }
    export PS1="$PS1$NO_COLOR \$(parse_git_branch)"
fi
```

## Debug trace

Output after commanding `set -x` and performing the steps to reproduce:

```
+ local cur prev words cword\;
+ _init_completion
+ local exclude= flag outx errx inx OPTIND=1
+ getopts n:e:o:i:s flag
+ COMPREPLY=()
+ local 'redir=@(?([0-9])<|?([0-9&])>?(>)|>&)'
+ _get_comp_words_by_ref -n '<>&' cur prev words cword
+ local exclude flag i OPTIND=1
+ words=()
+ local cur cword words
+ upargs=()
+ upvars=()
+ local upargs upvars vcur vcword vprev vwords
+ getopts c:i:n:p:w: flag -n '<>&' cur prev words cword
+ case $flag in
+ exclude='<>&'
+ getopts c:i:n:p:w: flag -n '<>&' cur prev words cword
+ [[ 6 -ge 3 ]]
+ case ${!OPTIND} in
+ vcur=cur
+ (( OPTIND += 1 ))
+ [[ 6 -ge 4 ]]
+ case ${!OPTIND} in
+ vprev=prev
+ (( OPTIND += 1 ))
+ [[ 6 -ge 5 ]]
+ case ${!OPTIND} in
+ vwords=words
+ (( OPTIND += 1 ))
+ [[ 6 -ge 6 ]]
+ case ${!OPTIND} in
+ vcword=cword
+ (( OPTIND += 1 ))
+ [[ 6 -ge 7 ]]
+ __get_cword_at_cursor_by_ref '<>&' words cword cur
+ words=()
+ local cword words
+ __reassemble_comp_words_by_ref '<>&' words cword
+ local exclude i j line ref
+ [[ -n <>& ]]
+ exclude='[<>&]'
+ printf -v cword %s 1
+ [[ -v exclude ]]
+ line='find AB -type f -exec chmod a-w '
+ (( i = 0, j = 0 ))
+ (( i < 7 ))
+ [[ 0 -gt 0 ]]
+ ref='words[0]'
+ printf -v 'words[0]' %s find
+ line=' AB -type f -exec chmod a-w '
+ (( i == COMP_CWORD ))
+ (( i++, j++ ))
+ (( i < 7 ))
+ [[ 1 -gt 0 ]]
+ [[ AB == +([<>&]) ]]
+ ref='words[1]'
+ printf -v 'words[1]' %s AB
+ line=' -type f -exec chmod a-w '
+ (( i == COMP_CWORD ))
+ printf -v cword %s 1
+ (( i++, j++ ))
+ (( i < 7 ))
+ [[ 2 -gt 0 ]]
+ [[ -type == +([<>&]) ]]
+ ref='words[2]'
+ printf -v 'words[2]' %s -type
+ line=' f -exec chmod a-w '
+ (( i == COMP_CWORD ))
+ (( i++, j++ ))
+ (( i < 7 ))
+ [[ 3 -gt 0 ]]
+ [[ f == +([<>&]) ]]
+ ref='words[3]'
+ printf -v 'words[3]' %s f
+ line=' -exec chmod a-w '
+ (( i == COMP_CWORD ))
+ (( i++, j++ ))
+ (( i < 7 ))
+ [[ 4 -gt 0 ]]
+ [[ -exec == +([<>&]) ]]
+ ref='words[4]'
+ printf -v 'words[4]' %s -exec
+ line=' chmod a-w '
+ (( i == COMP_CWORD ))
+ (( i++, j++ ))
+ (( i < 7 ))
+ [[ 5 -gt 0 ]]
+ [[ chmod == +([<>&]) ]]
+ ref='words[5]'
+ printf -v 'words[5]' %s chmod
+ line=' a-w '
+ (( i == COMP_CWORD ))
+ (( i++, j++ ))
+ (( i < 7 ))
+ [[ 6 -gt 0 ]]
+ [[ a-w == +([<>&]) ]]
+ ref='words[6]'
+ printf -v 'words[6]' %s a-w
+ line=' '
+ (( i == COMP_CWORD ))
+ (( i++, j++ ))
+ (( i < 7 ))
+ (( i == COMP_CWORD ))
+ local i cur= index=7 'lead=find AB'
+ [[ 7 -gt 0 ]]
+ [[ -n find AB ]]
+ [[ -n findAB ]]
+ cur='find AB -type f -exec chmod a-w '
+ (( i = 0 ))
+ (( i <= cword ))
+ [[ 32 -ge 4 ]]
+ [[ find != \f\i\n\d ]]
+ (( i < cword ))
+ local old_size=32
+ cur=' AB -type f -exec chmod a-w '
+ local new_size=28
+ (( index -= old_size - new_size ))
+ (( ++i ))
+ (( i <= cword ))
+ [[ 28 -ge 2 ]]
+ [[  A != \A\B ]]
+ cur='AB -type f -exec chmod a-w '
+ (( index > 0 ))
+ (( index-- ))
+ [[ 27 -ge 2 ]]
+ [[ AB != \A\B ]]
+ (( i < cword ))
+ (( ++i ))
+ (( i <= cword ))
+ [[ -n AB -type f -exec chmod a-w  ]]
+ [[ ! -n AB-typef-execchmoda-w ]]
+ (( index < 0 ))
+ local words cword cur
+ _upvars -a7 words find AB -type f -exec chmod a-w -v cword 1 -v cur AB
+ (( 15 ))
+ (( 15 ))
+ case $1 in
+ [[ -n 7 ]]
+ printf %d 7
+ [[ -n words ]]
+ unset -v words
+ eval 'words=("${@:3:7}")'
++ words=("${@:3:7}")
+ shift 9
+ (( 6 ))
+ case $1 in
+ [[ -n cword ]]
+ unset -v cword
+ eval 'cword="$3"'
++ cword=1
+ shift 3
+ (( 3 ))
+ case $1 in
+ [[ -n cur ]]
+ unset -v cur
+ eval 'cur="$3"'
++ cur=AB
+ shift 3
+ (( 0 ))
+ [[ -v vcur ]]
+ upvars+=("$vcur")
+ upargs+=(-v $vcur "$cur")
+ [[ -v vcword ]]
+ upvars+=("$vcword")
+ upargs+=(-v $vcword "$cword")
+ [[ -v vprev ]]
+ [[ 1 -ge 1 ]]
+ upvars+=("$vprev")
+ upargs+=(-v $vprev "${words[cword - 1]}")
+ [[ -v vwords ]]
+ upvars+=("$vwords")
+ upargs+=(-a${#words[@]} $vwords ${words+"${words[@]}"})
+ (( 4 ))
+ local cur cword prev words
+ _upvars -v cur AB -v cword 1 -v prev find -a7 words find AB -type f -exec chmod a-w
+ (( 18 ))
+ (( 18 ))
+ case $1 in
+ [[ -n cur ]]
+ unset -v cur
+ eval 'cur="$3"'
++ cur=AB
+ shift 3
+ (( 15 ))
+ case $1 in
+ [[ -n cword ]]
+ unset -v cword
+ eval 'cword="$3"'
++ cword=1
+ shift 3
+ (( 12 ))
+ case $1 in
+ [[ -n prev ]]
+ unset -v prev
+ eval 'prev="$3"'
++ prev=find
+ shift 3
+ (( 9 ))
+ case $1 in
+ [[ -n 7 ]]
+ printf %d 7
+ [[ -n words ]]
+ unset -v words
+ eval 'words=("${@:3:7}")'
++ words=("${@:3:7}")
+ shift 9
+ (( 0 ))
+ _variables
+ [[ AB =~ ^(\$(\{[!#]?)?)([A-Za-z0-9_]*)$ ]]
+ [[ AB =~ ^(\$\{[#!]?)([A-Za-z0-9_]*)\[([^]]*)$ ]]
+ [[ AB =~ ^\$\{[#!]?[A-Za-z0-9_]*\[.*]$ ]]
+ case ${prev-} in
+ return 1
+ [[ AB == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ [[ find == @(?([0-9])<|?([0-9&])>?(>)|>&) ]]
+ local i skip
+ (( i = 1 ))
+ (( i < 7 ))
+ [[ AB == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ (( i++ ))
+ (( 1 ))
+ (( i < 7 ))
+ [[ -type == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ (( i++ ))
+ (( 1 ))
+ (( i < 7 ))
+ [[ f == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ (( i++ ))
+ (( 1 ))
+ (( i < 7 ))
+ [[ -exec == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ (( i++ ))
+ (( 1 ))
+ (( i < 7 ))
+ [[ chmod == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ (( i++ ))
+ (( 1 ))
+ (( i < 7 ))
+ [[ a-w == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ (( i++ ))
+ (( 1 ))
+ (( i < 7 ))
+ (( cword <= 0 ))
+ prev=find
+ [[ -n '' ]]
+ return 0
+ local i
+ for i in ${!words[*]}
+ [[ find == -@(exec|ok)?(dir) ]]
+ for i in ${!words[*]}
+ [[ AB == -@(exec|ok)?(dir) ]]
+ for i in ${!words[*]}
+ [[ -type == -@(exec|ok)?(dir) ]]
+ for i in ${!words[*]}
+ [[ f == -@(exec|ok)?(dir) ]]
+ for i in ${!words[*]}
+ [[ -exec == -@(exec|ok)?(dir) ]]
+ _command_offset 5
+ local word_offset=5 i j
+ (( i = 0 ))
+ (( i < word_offset ))
+ (( j = 0 ))
+ (( j <= 32 ))
+ [[ find AB -type f -exec chmod a-w  == \f\i\n\d* ]]
+ break
+ COMP_LINE=' AB -type f -exec chmod a-w '
+ (( COMP_POINT -= 4 ))
+ (( i++ ))
+ (( i < word_offset ))
+ (( j = 0 ))
+ (( j <= 28 ))
+ [[  AB -type f -exec chmod a-w  == \A\B* ]]
+ COMP_LINE='AB -type f -exec chmod a-w '
+ (( COMP_POINT-- ))
+ (( j++ ))
+ (( j <= 27 ))
+ [[ AB -type f -exec chmod a-w  == \A\B* ]]
+ break
+ COMP_LINE=' -type f -exec chmod a-w '
+ (( COMP_POINT -= 2 ))
+ (( i++ ))
+ (( i < word_offset ))
+ (( j = 0 ))
+ (( j <= 25 ))
+ [[  -type f -exec chmod a-w  == \-\t\y\p\e* ]]
+ COMP_LINE='-type f -exec chmod a-w '
+ (( COMP_POINT-- ))
+ (( j++ ))
+ (( j <= 24 ))
+ [[ -type f -exec chmod a-w  == \-\t\y\p\e* ]]
+ break
+ COMP_LINE=' f -exec chmod a-w '
+ (( COMP_POINT -= 5 ))
+ (( i++ ))
+ (( i < word_offset ))
+ (( j = 0 ))
+ (( j <= 19 ))
+ [[  f -exec chmod a-w  == \f* ]]
+ COMP_LINE='f -exec chmod a-w '
+ (( COMP_POINT-- ))
+ (( j++ ))
+ (( j <= 18 ))
+ [[ f -exec chmod a-w  == \f* ]]
+ break
+ COMP_LINE=' -exec chmod a-w '
+ (( COMP_POINT -= 1 ))
+ (( i++ ))
+ (( i < word_offset ))
+ (( j = 0 ))
+ (( j <= 17 ))
+ [[  -exec chmod a-w  == \-\e\x\e\c* ]]
+ COMP_LINE='-exec chmod a-w '
+ (( COMP_POINT-- ))
+ (( j++ ))
+ (( j <= 16 ))
+ [[ -exec chmod a-w  == \-\e\x\e\c* ]]
+ break
+ COMP_LINE=' chmod a-w '
+ (( COMP_POINT -= 5 ))
+ (( i++ ))
+ (( i < word_offset ))
+ (( i = 0 ))
+ (( i <= COMP_CWORD - word_offset ))
+ (( i ))
+ (( i <= COMP_CWORD ))
+ unset 'COMP_WORDS[i]'
+ (( i++ ))
+ (( i <= COMP_CWORD ))
+ unset 'COMP_WORDS[i]'
+ (( i++ ))
+ (( i <= COMP_CWORD ))
+ (( COMP_CWORD -= word_offset ))
+ COMPREPLY=()
+ local cur
+ _get_comp_words_by_ref cur
+ local exclude flag i OPTIND=1
+ words=()
+ local cur cword words
+ upargs=()
+ upvars=()
+ local upargs upvars vcur vcword vprev vwords
+ getopts c:i:n:p:w: flag cur
+ [[ 1 -ge 1 ]]
+ case ${!OPTIND} in
+ vcur=cur
+ (( OPTIND += 1 ))
+ [[ 1 -ge 2 ]]
+ __get_cword_at_cursor_by_ref '' words cword cur
+ words=()
+ local cword words
+ __reassemble_comp_words_by_ref '' words cword
+ local exclude i j line ref
+ [[ -n '' ]]
+ printf -v cword %s -4
+ [[ -v exclude ]]
+ for i in "${!COMP_WORDS[@]}"
+ printf -v 'words[i]' %s -type
+ for i in "${!COMP_WORDS[@]}"
+ printf -v 'words[i]' %s f
+ for i in "${!COMP_WORDS[@]}"
+ printf -v 'words[i]' %s -exec
+ for i in "${!COMP_WORDS[@]}"
+ printf -v 'words[i]' %s chmod
+ for i in "${!COMP_WORDS[@]}"
+ printf -v 'words[i]' %s a-w
bash: COMP_POINT: substring expression < 0
+++ before_command
+++ echo -e -n '\e[0m'
++ history -a
+++ before_command
+++ echo -e -n '\e[0m'
++ history -r
++ parse_git_branch
++ git branch --no-color
++ sed -e '/^[^*]/d' -e 's/* \(.*\)/(git: \1)/'
```

**Comment by scop** [comment] 2021-11-04 20:25
Ouch, sorry for not remembering, this is likely a duplicate of #509, fixed in f1ddf810e4ee6693acb9fab1be1794586aa111a0. Can you confirm?

**Comment by leisti** [comment] 2021-11-04 20:37
Yes, it's a duplicate. I first reported it there as a comment, and asked if I should create a new bug report, and you said yes.

**Comment by scop** [comment] 2021-11-04 20:53
Aaaaaand I failed to notice #509 was where you asked. Making a mess here.

Anyway, your report says you're reproducing with 2.11, and the commit I'm pointing at above for the fix is fresher than that release. As said I cannot reproduce with current master, so I'm thinking it is indeed fixed. If you don't feel like trying out with current master, an easier alternative would be to apply the oneliner fix to your current version to try out.

**Comment by leisti** [comment] 2021-11-04 21:15
How do I test with the current master?

**Comment by leisti** [comment] 2021-11-05 13:08
This is what I tried to test the latest version of the master branch.

1. Cloned the master branch of this repository by commanding `git clone git@github.com:scop/bash-completion.git`.
2. Noticed that there's a script `bash_completion` in the repository's main directory.
3. Backed up file `/usr/share/bash-completion/bash_completion`, then copied the script from the repository on top of it.
4. Opened a new shell.

Note that my `~/.bashrc` file includes the lines

```
#### Enable the programmable TAB completion features.

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
  fi
fi
```

I added an `echo` command before the `source` commands, so am sure that the script being used is `/usr/share/bash-completion/bash_completion`.

5. Commanded `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`, and got the output `2.11.0`. This is the version of the script in the HEAD of the master branch of the repository.
6. Performed the steps to reproduce.

Result: the bug manifests itself again. See attached file trace.txt for the output after `set -x` has been commanded.

Is there an error in the above? Should I do something else to test against the version in the master branch?

**Comment by scop** [comment] 2021-11-05 22:08
The `find` completion is in `completions/find`, that needs to be replaced as well (actually the main `bash_completion` script would _not_ need replacing for this). Or as mentioned, the oneliner chnage from f1ddf81 (to your `/usr/share/bash-completion/completions/find`) would be all that's needed to try it out.

**Comment by scop** [comment] 2021-11-05 22:19
Aside, can't really recommend replacing your system installed files like that. For one off test, simply cloning bash-completion somewhere, cding to that dir, invoking a bash with no other version of bash-completion loaded (e.g. `bash --norc`) in that dir, then `. ./bash_completion` there and start trying things out should work for testing.

**Comment by leisti** [comment] 2021-11-06 18:04
Well, it was just a quick-and-dirty test, and after the test, I immediately replaced the modified `bash_completion` script by the original one.

I performed the test you suggested (using the quick-and-dirty method again), and this time, there was no error. So, the fix works, and the master of `bash-completion` package seemingly just hasn't made it to the Ubuntu packages yet.

Thanks for your help, and sorry for the waste of time. This issue can be closed.

**Comment by scop** [comment] 2021-11-07 20:37
NP, thanks for checking!

**Closed by scop** 2021-11-07 20:37 UTC
