### ISSUE TITLE
grep http `cat /tm<TAB> not completing

### ISSUE THREAD

**Issue by jidanni** [scop/bash-completion#282] opened 2019-02-21 21:10 UTC
```
$ grep http `cat /tm<TAB>
```
`doesn't complete /tmp here on Debian.

**Comment by gftg85** [comment] 2019-03-09 21:20
Duplicate of #151?

**Comment by scop** [comment] 2019-04-21 10:18
Yep, dupe of #151 indeed.

**Closed by scop** 2019-04-21 10:18 UTC
