### ISSUE TITLE
Unexpected EOF if $( preceded by anything

### ISSUE THREAD

**Issue by rcorre** [scop/bash-completion#8] opened 2016-02-28 12:04 UTC
Commands like the following:

    cat $(find ../<TAB>

will cause bash-completion to fail with `unexpected EOF while looking for matching ')'.` This is `bash-completion 2.1-5` on Archlinux.

**Comment by scop** [comment] 2016-02-28 12:15
Possibly already fixed in git, at least I cannot reproduce (but it
doesn't complete anything either). Can you test with the latest from
master branch?

**Comment by rcorre** [comment] 2016-02-28 12:54
Yes, this appears fixed in master. It would be nice if it offered completions but at least it doesn't crash.

**Closed** 2016-02-28 12:55 UTC
