### ISSUE TITLE
bash completion with scp and rsync for remote folders do not work with 2.13

### ISSUE THREAD

**Issue by slartibart70** [scop/bash-completion#1262] opened 2024-11-10 10:13 UTC
see also:
https://bugzilla.redhat.com/show_bug.cgi?id=2323521

The current 'fix' is to downgrade to 2.11
Then, we can use tab on remote-folders again, and the commandline-completion works

**Comment by akinomyoga** [comment] 2024-11-10 10:37
This is a duplicate of #1157 and already fixed by #1158. Please use 2.14.

**Closed by akinomyoga** 2024-11-10 10:37 UTC
Labels: duplicate
