### ISSUE TITLE
long option support for tar broken with version 2.4

### ISSUE THREAD

**Issue by bitstreamout** [scop/bash-completion#98] opened 2016-12-14 11:55 UTC
Try

`tar --create --file test.tar <TAB>`

does show only option but no files nor directories

`tar --create -f test.tar -<TAB>`
`-A  -c  -d  -r  -t  -u  -x`

 ...  the same for mixed options

`tar --create -f test.tar <TAB>`
`tar --create f test.tar <TAB>`

**Comment by bitstreamout** [comment] 2016-12-14 12:38
A patch
[x.txt](https://github.com/scop/bash-completion/files/651734/x.txt)

**Comment by scop** [comment] 2016-12-19 14:32
@bitstreamout Could you file a pull request along with test case demonstrating the failure and the fix for this?

@praiskup FYI

**Comment by akinomyoga** [comment] 2024-05-13 09:58
The issue is still present. Even worse, when completing the word `./`, it seems to produce the option names as filenames.

```bash
$ tar --create --file a.tar.gz ./[TAB]
./A  ./c  ./d  ./r  ./t  ./u  ./x
```

**Closed** 2024-08-23 09:40 UTC
